name: invink-expts
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13.2
  - pip:
      - gdown==5.2.0
      - datasets==3.4.1
      - huggingface-hub==0.35.3
      - mauve-text==0.4.0
      - numpy==2.2.4
      - pandas==2.2.3
      - pip==25.0.1
      - accelerate==1.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==3.4.1
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.57.0